### ISSUE TITLE
Falso fallo de checksum en bloque 10

### ISSUE THREAD

**Issue by imulilla** [nataliapc/makeTSX#4]
A veces da invalido el checksum de algunos bloques 10, parece que esta relacionado con el ser ultimo bloque.

Si se crea un wav con el bloque por duplicado, el primer bloque da ok y el segundo no.

Este fallo no afecta al parametro -i

Aparentemente se soluciona moviendo la linea 115 (chksum = lastChksum;) del B10_Standard_Ripper.cpp a la 127, encima de "cout << WAVTIME(pos) << "Extracted data: " << std::dec << (buff.size()) << " bytes" << endl;)

**Comment by nataliapc** [comment]
Algún wav en concreto donde ocurra esto?

**Comment by nataliapc** [comment]
Cambio aceptado. Gracias!
